create table community
(
    id bigint generated by default as identity,
    title varchar(30),
    content varchar(255),
    primary key (id)
);

insert into community(title, content) values ('하이','하이하이')

select * from community